FROM node:22-slim AS deps

WORKDIR /app/price

COPY price/package.json price/package-lock.json ./

RUN npm ci


FROM node:22-slim AS builder

WORKDIR /app/price

COPY --from=deps /app/price/node_modules ./node_modules
COPY price/. .

RUN npm run build


FROM node:22-slim AS runner

ENV NODE_ENV=production \
    TZ=America/Costa_Rica \
    PORT=3000

WORKDIR /app/price

COPY price/package.json price/package-lock.json ./
RUN npm ci --omit=dev

COPY --from=builder /app/price/.next ./.next
COPY --from=builder /app/price/public ./public
COPY --from=builder /app/price/next.config.ts ./next.config.ts

EXPOSE 3000

CMD ["npm", "run", "start"]
